### ISSUE TITLE
Unable to edit user settings

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_cycle#11]
Hey netniv,
as I described in another issue, my settings don't get applied:
![grafik](https://user-images.githubusercontent.com/28043745/47848101-87baca80-ddcd-11e8-830d-5e93b8f9e8fa.png)
But when I Go to the cycle tab, I get other settings:
![grafik](https://user-images.githubusercontent.com/28043745/47848127-9bfec780-ddcd-11e8-87b0-f892de170b8c.png)

I'm logged in as admin.

the SQL statements are:
![grafik](https://user-images.githubusercontent.com/28043745/47848153-b89aff80-ddcd-11e8-8b13-8a72570132a9.png)

![grafik](https://user-images.githubusercontent.com/28043745/47848164-c05aa400-ddcd-11e8-976e-e7293e7b3d39.png)

So you are right, the different users don't inherit the correct settings.

Am I supposed to change the values manually?

**Comment by netniV** [comment]
This has now been committed to the development code.
