### ISSUE TITLE
cycle fonts, legend etc. is fuzzy

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_cycle#12]
Hey guys, (hey netniv)
I'm on cacti 1.2 now and I don't like the cycle graphs. Cycle is a very important plugin to have all important graphs at one glance (plus rotating). So I think it's a crucial plugin for the decision to work with cacti.
![grafik](https://user-images.githubusercontent.com/28043745/47848596-25fb6000-ddcf-11e8-974d-a4199a07a521.png)
The fonts, axis' etc. are very small and fuzzy. It's very hard for my eyes.

In comparison a screenshot when I used cycle with cacti 0.8.8:
![grafik](https://user-images.githubusercontent.com/28043745/47848687-71ae0980-ddcf-11e8-85e6-93ce92cf2cb9.png)

That's a huge difference. The fonts, legend, axis' etc. are very easy to read.

**Comment by netniV** [comment]
You appear to be comparing different graphs, so you will likely have a scaling issue when using the same fixed size.  Your legend is larger on the first set of graphs which will reduce the size of the area for the graph.

**Comment by Axel577** [comment]
No, look at that:
![grafik](https://user-images.githubusercontent.com/28043745/47849938-c5baed00-ddd3-11e8-9c90-50d4c5aa3807.png)



believe me, I tried every combination of width and height, the fonts are always awful. 
I'm wondering if I'm the only one who uses cycle.

**Comment by netniV** [comment]
Check what settings you have for the secontion 'RRDtool Graph Font Control' under the Visual tab.  They are completely customisable from what I've seen.  Also, make sure you are setting Cycle's options in your profile settings, not the global settings (which are defaults for new users)

**Comment by Axel577** [comment]
Mark, believe me, that is not the problem.
Here's another example: 
That's the graph when I'm in the graphs tree tab:
![grafik](https://user-images.githubusercontent.com/28043745/47850066-3bbf5400-ddd4-11e8-9368-48bd3efb4d04.png)
It's 150x500.

When I'm in cycle tab, the same graph looks like that (also 150x500):
![grafik](https://user-images.githubusercontent.com/28043745/47850292-07986300-ddd5-11e8-98e5-fd7a5bd0dc84.png)

That's a difference like day and night.

When I want to have the same seize in cycle, I have to set 250x600. Then it looks like that:
![grafik](https://user-images.githubusercontent.com/28043745/47850406-5f36ce80-ddd5-11e8-8b71-d3a87ff8f913.png)

still a difference like day and night.

I hope you now understand what I'm trying to say.

**Comment by Axel577** [comment]
The problem seems to be the graphing field itself. It's much bigger than in graphs tree section, so there is not that much space for the legend and header etc.
Those things get squeezed und thus become fuzzy.

**Comment by Axel577** [comment]
Here is the direct comparison:
![grafik](https://user-images.githubusercontent.com/28043745/48268070-490fba80-e434-11e8-9a8b-3f5003a09e57.png)
In graph tree, the graph axis is from 0 - 20 - 40 - 60 - 80 - 100 GB
In cycle: 0 - 10 - 20 - 30 - 40 - 50 - 60 - 70 - 80 - 90 - 100 GB
That's the problem. The graph itself is much bigger, therefore legend and headline don't have space.

Does anyone else have this problem or is my cacti installation messed up?
Respectively, can the developer of cycle plugin change that?

**Comment by netniV** [comment]
Are you using thumbnail mode when viewing in the graph tree?

**Comment by Axel577** [comment]
No, I don't use thumbnails:
![grafik](https://user-images.githubusercontent.com/28043745/48274300-51bbbd00-e443-11e8-9e20-c95e5bf72a5f.png)

**Comment by Axel577** [comment]
Can you post me a screenshot how cycle look in your 1.2 installation? Do you have the same issue? Maybe it's again a problem of some old files, like Chart.js in the dashboard issue.

**Comment by netniV** [comment]
I'm thinking it may be more that it is using the thumbnail option with legend enabled.  If you use thumbnail on the graph page, it removes the legend.

**Comment by Axel577** [comment]
You are right. 
But as I said in my first post, when I used cycle with cacti 0.8.8, everything was fine. Cycle showed the graph 1:1 as in the graphs tree.
So something changed since 0.8.8. Either on cycle, or on cacti. Or a combination of both.

**Comment by Axel577** [comment]
@netniV Who is the programmer of cycle?

**Comment by netniV** [comment]
There have been a few contributions but most recent commits are unfortunately mine :)

**Comment by Axel577** [comment]
What do you think how big is the chance that cacti 1.2 gets a great cycle plugin again? Maybe you can discuss that in your group. I think a tool like cycle where you can see all important graphs (plus rotation) is a crucial thing. Most admins have big screens where they want to see all graphs at a glance. It would also raise the reputation and usage of cacti.
Speaking of me, I would already be satisfied if cycle shows the graphs without that hidden thumbnail view that makes those hard to read. I'm not a programmer, but I think that's not a big deal.

**Comment by Axel577** [comment]
@xmacan maybe you can help out here? You do a great job with intropage. Maybe here, too?
I mean, you can select single graphs to appear at the intropage site, cycle is kinda the same, isn't it?

**Comment by xmacan** [comment]
hmmm, I was thinking about extension of Intropage - I wanted add tabs like upper menu in cacti. Second tab should be  exactly as cycle plugin. Now it is unnecessary. I have never heard about cycle until today :-) 

I can look at it, but it will not be soon :-( I still have 1.1.38 and a lot of work.

**Comment by Axel577** [comment]
I like the idea to extend intropage! Go for that instead of updating cycle. I mean, if intropage shows selected graphs on an extra site, that's great. Noone will need cycle then.

**Comment by netniV** [comment]
@Axel577 I will get around to figuring it out, it's just a matter of time.  Over the christmas period, I have two big sets of VM migrations, plus the Cacti release and plugin updates for that release... so it's on the cards just probably not as quick as you'd like ;-)

**Comment by Axel577** [comment]
@netniV it's okay when it takes some time, I can live with that. Until now, you didn't appear to be eager for taking care about cycle. But that seemed to be wrong. When I know that you will take care about it, I'm happy :) That was the missing answer ;-)

**Comment by Axel577** [comment]
@netniV Hey Mark, did you already have time to figure it out?

**Comment by netniV** [comment]
Not yet but this is plugin month, before 1.3 starts.  I've been working through some of the plugins, cycle is on the list especially given that I tested this at the office yesterday and it wasn't working at all, just displayed the filter table with no count down.

I was sure I'd figured out that issue already so something must have tripped it again.

**Comment by Axel577** [comment]
@netniV do you have news?

**Comment by netniV** [comment]
Sorry, not yet.  I will try and look this week though. It's been hectic between various projects we have to try and improve our infrastructure.  I'll examine the URLs being generated by both systems and then compare what is being passed.

**Comment by Axel577** [comment]
@netniV Hey netniv, any news on that?

**Comment by netniV** [comment]
We were actually having a discussion on it yesterday.  But we didn't come to a resolution.  I know I've kept putting this off so I'll make it a priority this week once I've released 1.2.4

**Comment by TUISTERa** [comment]
Hello, is this an issue or it was fixed already ? Is plugin working on Cacti 1.2.8?

**Comment by netniV** [comment]
The plugin works but the above user felt that the fonts where not showing the same under cycle as they did under cacti core. 

Due to a change in circumstances it hasn’t been revisited yet.

**Comment by cigamit** [comment]
I've switched to SVG rendering.  The graphs resize pretty nice in that case.  I'm not using Cycle though.

**Comment by Axel577** [comment]
@cigamit What is SVG rendering and where can I get it from?

**Comment by netniV** [comment]
SVG is a different format to PNG as it's scalable in size as its vector based (says how things curve - or don't curve).  PNG is a rasterized format so it pixelates when growing because as you need more pixels, imaging software * guesses * what to fill in to make the image larger.

**Comment by TheWitness** [comment]
You can bulk change the image format from the 1.2.x branch by changing a templates options and choosing SVG instead of PNG.  So, once 1.2.29 is released, you can switch in less than a minute to SVG.
