### ISSUE TITLE
Graphs not shown until browser page recycled

### ISSUE THREAD

**Issue by jayaich** [Cacti/plugin_cycle#13]
Hello,

We have just upgraded Cacti from version 1.1.38 to 2.2.1, and have installed the latest cycle plugin code. However, when I log into cacti and click on the 'cycle' tab, nothing is shown except the header part - showing the 'prev', 'next', stop' buttons etc. No graphs are shown and no message about their being no graphs. If I select a part of the tree which has graphs still nothing is shown. Clicking the cycle 'refresh' button makes no difference.

However, if I click on the browser 'reload current page' button, then I get the expected output - either graphs or a message about their being no graphs.

Using a browser console it looks like the javascript code in cycle.php is throwing up an error:

`jQuery.Deferred exception: timerID is not defined @https://cacti.tis.plymouth.ac.uk/cacti/index.php 
 line 111 > scriptElement:42:4
mightThrow@https://cacti.tis.plymouth.ac.uk/cacti/include/js/jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:3534:21
resolve/</process<@https://cacti.tis.plymouth.ac.uk/cacti/include/js/jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:3602:12
 undefined jquery.js:3818:3

ReferenceError: timerID is not defined`

Looking at the web page source code I can see that the 'cycle.js' is included in the head section:

'<head>
...
<script type='text/javascript' src='/cacti/plugins/cycle/cycle.js'></script>`

I have taken a look into this problem, but cannot see why it fails. If I modify cycle.php to use the above 'script type...' line in the body sectoin, it makes no difference. If I use it in the section where timerID is used, then it still doesn't work. No errors, but the change makes no difference.

**Comment by netniV** [comment]
I shall take a look.  Because the whole page does not get refreshed on every click now, it may need adjusting whether the JS is included.

**Comment by jayaich** [comment]
Wow! A very quick reply! Thanks for that (the reply and taking a look).

**Comment by netniV** [comment]
The latest development version should solve this for you.

**Comment by jayaich** [comment]
Yes, but...
when I first click on the 'cycle' tab it takes me to the 'Top Level' of a tree which has no graphs. This is not a problem, but I was expecting the page to say 'No graphs matching criteria'. Instead it is just a blank page (no graphs).
Also, while on the no graphs page the 'start' button seems to be enabled. If I click on it it seems to start the countdown. I would have thought it might be greyed-out when there are no graphs.

**Comment by netniV** [comment]
No, because there may be graphs added whilst cycling :)
