### ISSUE TITLE
PLUGIN WARNING: Function does not exist config_form with function cycle_config_form

### ISSUE THREAD

**Issue by bonj1987** [Cacti/plugin_cycle#19]
if i turn my debug to medium, and i select the HMIB plug in to log, so i can troubleshoot it.. this error comes up.
i dont know why it references cycle... but i thought i'd throw this here for you to look at

the error i get is  
PLUGIN WARNING: Function does not exist config_form with function cycle_config_form , and it shows up every second i have that logging set to medium.

**Comment by netniV** [comment]
I'm not sure if this was fixed already be we can take a look.

**Comment by TheWitness** [comment]
I just cloned.  It's still there.  I'll do a quick fix.

**Comment by TheWitness** [comment]
This should be resolved in Develop.  Just grab a fresh copy of the plugin.

**Comment by bonj1987** [comment]
confirmed. put new version in place. turned logging to medium and i no longer get that error. thanks for the quick work!

**Comment by bonj1987** [comment]
confirmed.. fix is in and working. thanks for the quick response!

**Comment by TheWitness** [comment]
Cool.
