### ISSUE TITLE
cycle bad graph resolution

### ISSUE THREAD

**Issue by Axel577** [Cacti/plugin_cycle#2]
Hi!
I installed cycle 4.0 on cacti 1.1.13.
The graphs have a very bad resolution though:
![cycle1](https://user-images.githubusercontent.com/28043745/28816149-0597de4e-76a4-11e7-87d4-427b1d9c2ca9.JPG)

in comparison cacti 0.8.8:
![cycle1](https://user-images.githubusercontent.com/28043745/28815413-9bfc4788-76a1-11e7-89cc-ef41845b6a64.JPG)

You can hardly read the letters.
Can someone help me?

**Comment by cigamit** [comment]
Change your resolution from 200x700 to some thing that will make the text larger.

**Comment by thurban** [comment]
Fixed in latest git version ( https://github.com/Cacti/plugin_cycle/commit/45623890056ee3745c7425750ca7996c63684454 )
