### ISSUE TITLE
Cycle not hourouring "Display Legend" setting

### ISSUE THREAD

**Issue by BigAl101** [Cacti/plugin_cycle#3]
Set the "Display Legend" option under "Settings -> Cycle" but whenever I navigate to the cycle page the graphs legends are not displayed.

If i then tick the "Legend" tick box between the Next button and Refresh button the legends display. 

I then click the save button.

Navigate away from cycle to anther page, i.e graphs, monitor etc and go back to cycle and the legends are missing.

**Comment by cigamit** [comment]
This should be fixed now.  It was a pretty large overhaul to this plugin.  The program flow is much better now as well.
