### ISSUE TITLE
Lot's of errors in cacti log from Cycle

### ISSUE THREAD

**Issue by BigAl101** [Cacti/plugin_cycle#4]
Cacti log is filled with errors from cycle.
Cycle rotation type is set to Specific List with a list of valid graph ID's, graphs do display/cycle but fills the cacti log with errors.

I've tried changing the rotation type to  "Legacy (All)" and "Tree Mode" but still getting errors.

I'm using the latest cycle plugin from github and had this error on 1.1.17 and have just updated to 1.1.19 (EPEL7 repo) and am still gettign the same issue.

08/09/2017 11:38:17 - CMDPHP SQL Backtrace: (/plugins/cycle/cycle_ajax.php: 69 get_next_graphid)(/plugins/cycle/functions.php: 414 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 386 cacti_debug_backtrace)
--
08/09/2017 11:38:17 - DBCALL ERROR: SQL Assoc Failed!, Error: Got error 'empty (sub)expression' from regexp
08/09/2017 11:38:17 - DBCALL ERROR: SQL Assoc Failed!, Error:1139, SQL:'SELECT gl.id, gtg.title_cache FROM graph_local AS gl INNER JOIN graph_templates_graph AS gtg ON (gtg.local_graph_id=gl.id) WHERE gl.id<5986 AND gtg.title_cache RLIKE '' ORDER BY id DESC LIMIT 0, 4'
08/09/2017 11:38:17 - CMDPHP SQL Backtrace: (/plugins/cycle/cycle_ajax.php: 69 get_next_graphid)(/plugins/cycle/functions.php: 345 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 386 cacti_debug_backtrace)
08/09/2017 11:38:17 - DBCALL ERROR: SQL Assoc Failed!, Error: Got error 'empty (sub)expression' from regexp
08/09/2017 11:38:17 - DBCALL ERROR: SQL Assoc Failed!, Error:1139, SQL:'SELECT gl.id, gtg.title_cache FROM graph_local AS gl INNER JOIN graph_templates_graph AS gtg ON (gtg.local_graph_id=gl.id) WHERE gtg.title_cache RLIKE '' ORDER BY gl.id ASC LIMIT 0, 4'
08/09/2017 11:38:05 - CMDPHP SQL Backtrace: (/plugins/cycle/cycle_ajax.php: 69 get_next_graphid)(/plugins/cycle/functions.php: 414 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 386 cacti_debug_backtrace)
08/09/2017 11:38:05 - DBCALL ERROR: SQL Assoc Failed!, Error: Got error 'empty (sub)expression' from regexp
08/09/2017 11:38:05 - DBCALL ERROR: SQL Assoc Failed!, Error:1139, SQL:'SELECT gl.id, gtg.title_cache FROM graph_local AS gl INNER JOIN graph_templates_graph AS gtg ON (gtg.local_graph_id=gl.id) WHERE gl.id<17 AND gtg.title_cache RLIKE '' ORDER BY id DESC LIMIT 0, 4'
08/09/2017 11:37:16 - CMDPHP SQL Backtrace: (/plugins/cycle/cycle_ajax.php: 69 get_next_graphid)(/plugins/cycle/functions.php: 414 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 386 cacti_debug_backtrace)
08/09/2017 11:37:16 - DBCALL ERROR: SQL Assoc Failed!, Error: Got error 'empty (sub)expression' from regexp
08/09/2017 11:37:16 - DBCALL ERROR: SQL Assoc Failed!, Error:1139, SQL:'SELECT gl.id, gtg.title_cache FROM graph_local AS gl INNER JOIN graph_templates_graph AS gtg ON (gtg.local_graph_id=gl.id) WHERE gl.id<5986 AND gtg.title_cache RLIKE '' ORDER BY id DESC LIMIT 0, 4'
08/09/2017 11:37:16 - CMDPHP SQL Backtrace: (/plugins/cycle/cycle_ajax.php: 69 get_next_graphid)(/plugins/cycle/functions.php: 345 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 386 cacti_debug_backtrace)
08/09/2017 11:37:16 - DBCALL ERROR: SQL Assoc Failed!, Error: Got error 'empty (sub)expression' from regexp
08/09/2017 11:37:16 - DBCALL ERROR: SQL Assoc Failed!, Error:1139, SQL:'SELECT gl.id, gtg.title_cache FROM graph_local AS gl INNER JOIN graph_templates_graph AS gtg ON (gtg.local_graph_id=gl.id) WHERE gtg.title_cache RLIKE '' ORDER BY gl.id ASC LIMIT 0, 4'

**Comment by cigamit** [comment]
Should be resolved.
