### ISSUE TITLE
Graphs not cycling.

### ISSUE THREAD

**Issue by memattevans** [Cacti/plugin_cycle#8]
Graphs are not moving to the next set. I can manually change it to the next set, but when the change time is reached it will revert back to the first set of graphs.

Cacti version 1.1.22 - setup from source.
Spine version 1.1.21 - setup from source.
OS Debian 9
I have tried with Google Chrome Version 61.0.3163.79 and Firefox Version 55.03.

**Comment by memattevans** [comment]
Cacti Server OS is Debian 9.

**Comment by cigamit** [comment]
If using Chrome, you will have to manualy update the cycle.css file by browsing to it.  Chrome does not easily refresh javascript files.

**Comment by memattevans** [comment]
I am not finding a cycle.css. Maybe I am missing it, could you tell me where it should be located?

**Comment by cigamit** [comment]
It's cycle.js in the base of the cycle plugin directory.  Try with Firefox first and hit F5 to refresh.

**Comment by cigamit** [comment]
Just noticed this behavior.  Did all those updates so fast that I forget to see if the plugin actually worked.

**Comment by cigamit** [comment]
Okay, resolved now.

**Comment by KnoAll** [comment]
I am having this issue. I have updated to 4.1 of the plugin but on multiple Win10 machines in both Chrome and Firefox my graphs are not cycling at all.

**Comment by KnoAll** [comment]
After doing some fiddling, I have found that if the number of graphs to display is less than the number of graphs selected the graphs do not refresh. For example, if the number of graphs to display is set to 30, but there are only 22 graphs in the selected group, it will not refresh. If then set to display 20, then it refreshes as expected.
